export const cityIATA = [
    { value: "DEL", label: "New Delhi" },
    { value: "BOM", label: "Mumbai" },
    { value: "BLR", label: "Bangalore" },
    { value: "HYD", label: "Hyderabad" },
    { value: "CCU", label: "Kolkata" },
    { value: "AMD", label: "Ahmadabad" },
    { value: "LKO", label: "Lucknow" },
    { value: "IXL", label: "Leh" },
    { value: "BHO", label: "Bhopal" },
    { value: "IXR", label: "Ranchi" },
    { value: "GAU", label: "Guwahati" },
    { value: "IXC", label: "Chandigarh" },
    { value: "UDR", label: "Udaipur" },
    { value: "GOI", label: "Goa" },
    { value: "DAI", label: "Darjeeling" },
    { value: "DED", label: "Dehra Dun" },
    { value: "IDR", label: "Indore" },
    { value: "DHM", label: "Dharamsala" },
    { value: "HSS", label: "Hissar" },
    { value: "PAT", label: "Patna" },
    { value: "ATQ", label: "Amritsar" },
    { value: "JAI", label: "Jaipur" },
    { value: "IXJ", label: "Jammu" },
    { value: "SXR", label: "Srinagar" },
    { value: "TRV", label: "Trivandrum" },
]